name: gapoktan_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  chewie: ^1.3.1
  cupertino_icons: ^1.0.4
  dotted_border: ^2.0.0+2
  dropdown_button2: ^1.2.2
  flutter:
    sdk: flutter
  flutter_icons: ^1.1.0
  flutter_image_compress: ^1.1.0
  flutter_login: ^3.1.0
  flutter_svg: ^1.0.3
  get: 4.6.1
  get_storage: ^2.0.3
  getwidget: ^2.0.4
  image_cropper: ^1.5.1
  image_picker: ^0.8.4+11
  intl: ^0.17.0
  video_player: ^2.3.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
